const fs = require("fs");
const minify = require("html-minifier").minify;

const filePath = "dist/index.html";

fs.readFile(filePath, "utf8", (err, data) => {
    if (err) {
        return console.error(`Error reading file: ${err.message}`);
    }

    const minifiedValue = minify(data, {
        caseSensitive: false,
        collapseBooleanAttributes: true,
        collapseInlineTagWhitespace: false,
        collapseWhitespace: true,
        conservativeCollapse: false,
        decodeEntities: true,
        html5: true,
        includeAutoGeneratedTags: false,
        keepClosingSlash: false,
        minifyCSS: true,
        minifyJS: true,
        preserveLineBreaks: false,
        preventAttributesEscaping: false,
        processConditionalComments: true,
        processScripts: ["text/html"],
        removeAttributeQuotes: true,
        removeComments: true,
        removeEmptyAttributes: true,
        removeEmptyElements: false,
        removeOptionalTags: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        removeTagWhitespace: true,
        sortAttributes: true,
        sortClassName: true,
        trimCustomFragments: true,
        useShortDoctype: true,
    });

    fs.writeFile(filePath, minifiedValue, "utf8", (err) => {
        if (err) {
            return console.error(`Error writing file: ${err.message}`);
        }

        const originalSize = data.length;
        const minifiedSize = minifiedValue.length;
        const sizeDifference = originalSize - minifiedSize;
        const savingsPercentage = ((sizeDifference / originalSize) * 100).toFixed(2);

        console.log(
            `Successfully minified '${filePath}'. Original size: ${originalSize}. Minified size: ${minifiedSize}. Savings: ${sizeDifference} bytes (${savingsPercentage}%)`
        );
    });
});
