export const countriesList = {
  currenciesArray: [
    {
      name: "Leva",
      currency: "BGN",
      price: 1.96,
      symbol: "лв.",
      alignSymbolEnd: true,
    },
    {
      name: "Euro",
      currency: "EUR",
      price: 1,
      symbol: "€",
      alignSymbolEnd: false,
    },
    //{ name: "Dollar", currency: "USD", price: 1.09, symbol: "$", alignSymbolEnd: false },
  ],

  languagesArray: [
    { name: "Български", code: "bg" },
    { name: "English", code: "en" },
  ],

  shippingAvaliableTo2: [
    "Afghanistan",
    "Åland Islands",
    "Albania",
    "Algeria",
    "American Samoa",
    'Andorra"',
    'Angola"',
    "Anguilla",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands",
    'Faroe Islands"',
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-bissau",
    "Guyana",
    "Haiti",
    "Heard Island and Mcdonald Islands",
    "Holy See (Vatican City State)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    'Ireland"',
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, Democratic People`s Republic",
    'Kuwait"',
    "Kyrgyzstan",
    "Latvia",
    "Lebanon",
    'Lesotho"',
    "Liberia",
    "Libyan Arab Jamahiriya",
    "Liechtenstein",
    'Lithuania" > Lithuania',
    'Luxembourg" > Luxembourg',
    'Macao" > Macao',
    "Macedonia",
    'Madagascar" > Madagascar',
    'Malawi" > Malawi',
    'Malaysia" > Malaysia',
    'Maldives" > Maldives',
    'Mali" > Mali',
    'Malta" > Malta',
    'Marshall Islands" > Marshall Islands',
    'Martinique" > Martinique',
    'Mauritania" > Mauritania',
    'Mauritius" > Mauritius',
    'Mayotte" > Mayotte',
    'Mexico" > Mexico',
    "Micronesia",
    'Monaco" > Monaco',
    'Mongolia" > Mongolia',
    'Montenegro" > Montenegro',
    'Montserrat" > Montserrat',
    'Morocco" > Morocco',
    'Mozambique" > Mozambique',
    'Myanmar" > Myanmar',
    'Namibia" > Namibia',
    'Nauru" > Nauru',
    'Nepal" > Nepal',
    'Netherlands" > Netherlands',
    'Netherlands Antilles" > Netherlands Antilles',
    'New Caledonia" > New Caledonia',
    'New Zealand" > New Zealand',
    'Nicaragua" > Nicaragua',
    'Niger" > Niger',
    'Nigeria" > Nigeria',
    'Niue" > Niue',
    'Norfolk Island" > Norfolk Island',
    'Northern Mariana Islands" > Northern Mariana Islands',
    'Norway" > Norway',
    'Oman" > Oman',
    'Pakistan" > Pakistan',
    'Palau" > Palau',
    "Palestinian",
    'Panama" > Panama',
    'Papua New Guinea" > Papua New Guinea',
    'Paraguay" > Paraguay',
    'Peru" > Peru',
    'Philippines" > Philippines',
    'Pitcairn" > Pitcairn',
    'Poland" > Poland',
    'Portugal" > Portugal',
    'Puerto Rico" > Puerto Rico',
    'Qatar" > Qatar',
    'Reunion" > Reunion',
    'Romania" > Romania',
    'Russian Federation" > Russian Federation',
    'Rwanda" > Rwanda',
    'Saint Helena" > Saint Helena',
    'Saint Kitts and Nevis" > Saint Kitts and Nevis',
    'Saint Lucia" > Saint Lucia',
    'Saint Pierre and Miquelon" > Saint Pierre and Miquelon',
    "Saint Vincent and The Grenadines",
    'Samoa" > Samoa',
    'San Marino" > San Marino',
    'Sao Tome and Principe" > Sao Tome and Principe',
    'Saudi Arabia" > Saudi Arabia',
    'Senegal" > Senegal',
    'Serbia" > Serbia',
    'Seychelles" > Seychelles',
    'Sierra Leone" > Sierra Leone',
    'Singapore" > Singapore',
    'Slovakia" > Slovakia',
    'Slovenia" > Slovenia',
    'Solomon Islands" > Solomon Islands',
    'Somalia" > Somalia',
    'South Africa" > South Africa',
    "South Georgia and The South Sandwich Islands",
    'Sri Lanka" > Sri Lanka',
    'Sudan" > Sudan',
    'Suriname" > Suriname',
    'Svalbard and Jan Mayen" > Svalbard and Jan Mayen',
    'Swaziland" > Swaziland',
    'Sweden" > Sweden',
    'Switzerland" > Switzerland',
    'Syrian Arab Republic" > Syrian Arab Republic',
    'Taiwan" > Taiwan',
    'Tajikistan" > Tajikistan',
    "Tanzania",
    'Thailand" > Thailand',
    'Timor-leste" > Timor - leste',
    'Togo" > Togo',
    'Tokelau" > Tokelau',
    'Tonga" > Tonga',
    'Trinidad and Tobago" > Trinidad and Tobago',
    'Tunisia" > Tunisia',
    'Turkey" > Turkey',
    'Turkmenistan" > Turkmenistan',
    'Turks and Caicos Islands" > Turks and Caicos Islands',
    'Tuvalu" > Tuvalu',
    'Uganda" > Uganda',
    'Ukraine" > Ukraine',
    'United Arab Emirates" > United Arab Emirates',
    "United Kingdom",
    "United States",
    'Uzbekistan" > Uzbekistan',
    'Vanuatu" > Vanuatu',
    'Venezuela" > Venezuela',
    'Viet Nam" > Viet Nam',
    'Virgin Islands, British" > Virgin Islands, British',
    "Virgin Islands, U.S",
    'Western Sahara" > Western Sahara',
    'Yemen" > Yemen',
    'Zambia" > Zambia',
    'Zimbabwe" > Zimbabwe',
  ],

  shippingAvaliableTo: ["europeCountries"],

  europeCountries: [
    { label: "Bulgaria", image: "currency-flag currency-flag--bg", icon: true },
  ],
  usaCountries: [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "vRhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  canadaCountries: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon",
  ],
};
